project:
  type: website
  resources:
    - CNAME

website:
  title: "Juan Masullo J."
  site-url: https://juanmasullo.com
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Publications
        href: publications.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css">

